version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 33000:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 33001:6379

volumes:
  mysql-data: {}
